spring.data.mongodb.uri=mongodb://bot:ejEHTvZ5TCAXb8cPtYyybJU2MCxsugCgN9zkAy377CGFLteWch@94.228.117.129:27017/weather_telegram_bot

server.servlet.encoding.charset = UTF-8
server.servlet.encoding.enabled = true
server.servlet.encoding.force = true
spring.mandatory-file-encoding = UTF-8
server.tomcat.uri-encoding = UTF-8
spring.messages.encoding = UTF-8

server.port=8002
